name: Regression

on:
  # Manually run
  workflow_dispatch:
    inputs:
      services:
        description: 'Choose a service to do regression against'
        type: choice
        options:
          - Pet
        required: false

  # Reserve the ability to do regression by receiving external event like from webhook
  repository_dispatch:

  # Daily regression
  schedule:
    - cron: '0 21 * * *' # run at UTC 09:00 PM every day (Sydney 07:00 AM).


jobs:
  regression:
    timeout-minutes: 40
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      
      - name: Install dependencies
        run: npm install

      - name: Run test scripts
        run: |
          if [ ! -z ${{ inputs.services }} ];
          then
            npm test -- --grep ${{ inputs.services }}
          else
            npm test

      - name: Upload test repor as artifact
        uses: actions/upload-artifact@v3
        with:
          name: testReport for ${{ inputs.services }}
          path: ${{ github.workspace }}/mochawesome-report
